[package]
name = "test_go"
version = "0.1.0"
authors = ["Luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
